package com.replica.replicaisland.ui

object PreferenceConstants {
    const val PREFERENCE_LEVEL_ROW = "levelRow"
    const val PREFERENCE_LEVEL_INDEX = "levelIndex"
    const val PREFERENCE_LEVEL_COMPLETED = "levelsCompleted"
    const val PREFERENCE_SOUND_ENABLED = "enableSound"
    const val PREFERENCE_SAFE_MODE = "safeMode"
    const val PREFERENCE_SESSION_ID = "session"
    const val PREFERENCE_LAST_VERSION = "lastVersion"
    const val PREFERENCE_STATS_ENABLED = "enableStats"
    const val PREFERENCE_CLICK_ATTACK = "enableClickAttack"
    const val PREFERENCE_TILT_CONTROLS = "enableTiltControls"
    const val PREFERENCE_TILT_SENSITIVITY = "tiltSensitivity"
    const val PREFERENCE_MOVEMENT_SENSITIVITY = "movementSensitivity"
    const val PREFERENCE_SCREEN_CONTROLS = "enableScreenControls"
    const val PREFERENCE_ENABLE_DEBUG = "enableDebug"
    const val PREFERENCE_TOTAL_GAME_TIME = "totalGameTime"
    const val PREFERENCE_LAST_ENDING = "lastEnding"
    const val PREFERENCE_ROBOTS_DESTROYED = "robotsDestroyed"
    const val PREFERENCE_PEARLS_COLLECTED = "pearlsCollected"
    const val PREFERENCE_PEARLS_TOTAL = "pearlsTotal"
    const val PREFERENCE_LINEAR_MODE = "linearMode"
    const val PREFERENCE_EXTRAS_UNLOCKED = "extrasUnlocked"
    const val PREFERENCE_DIFFICULTY = "difficulty"
    const val PREFERENCE_LEFT_KEY = "keyLeft"
    const val PREFERENCE_RIGHT_KEY = "keyRight"
    const val PREFERENCE_ATTACK_KEY = "keyAttack"
    const val PREFERENCE_JUMP_KEY = "keyJump"
    const val PREFERENCE_NAME = "ReplicaIslandPrefs"
}